apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: headwind
spec:
  version: v0.1.1
  homepage: https://headwind.sh
  shortDescription: Kubernetes workload update automation
  description: |
    Headwind automates Kubernetes workload updates based on container image
    changes with approval workflows and rollback capabilities.

    Features:
    - Automated workload updates for Deployments, StatefulSets, DaemonSets, and HelmReleases
    - Approval workflow for controlled updates
    - Semantic versioning policies (patch, minor, major)
    - Rollback support
    - Slack/Teams/webhook notifications
    - Comprehensive observability with Prometheus metrics

    This plugin provides CLI commands to interact with the Headwind operator
    installed in your cluster.
  caveats: |
    This plugin requires the Headwind operator to be installed in your cluster.

    Install the operator with Helm:
      helm repo add headwind https://headwind.sh/charts
      helm repo update
      helm install headwind headwind/headwind -n headwind-system --create-namespace

    Or install from the manifest:
      kubectl apply -f https://github.com/headwind-sh/headwind/releases/download/v0.1.1/headwind.yaml

    For detailed documentation, visit: https://headwind.sh/docs
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/headwind-sh/headwind/releases/download/v0.1.1/kubectl-headwind-linux-amd64.tar.gz
    sha256: PLACEHOLDER_LINUX_AMD64
    bin: kubectl-headwind
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    uri: https://github.com/headwind-sh/headwind/releases/download/v0.1.1/kubectl-headwind-linux-arm64.tar.gz
    sha256: PLACEHOLDER_LINUX_ARM64
    bin: kubectl-headwind
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/headwind-sh/headwind/releases/download/v0.1.1/kubectl-headwind-darwin-amd64.tar.gz
    sha256: PLACEHOLDER_DARWIN_AMD64
    bin: kubectl-headwind
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    uri: https://github.com/headwind-sh/headwind/releases/download/v0.1.1/kubectl-headwind-darwin-arm64.tar.gz
    sha256: PLACEHOLDER_DARWIN_ARM64
    bin: kubectl-headwind
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/headwind-sh/headwind/releases/download/v0.1.1/kubectl-headwind-windows-amd64.exe.tar.gz
    sha256: PLACEHOLDER_WINDOWS_AMD64
    bin: kubectl-headwind.exe
  - selector:
      matchLabels:
        os: windows
        arch: arm64
    uri: https://github.com/headwind-sh/headwind/releases/download/v0.1.1/kubectl-headwind-windows-arm64.exe.tar.gz
    sha256: PLACEHOLDER_WINDOWS_ARM64
    bin: kubectl-headwind.exe
