---
# HelmRepository for JFrog OCI
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jfrog-oci
  namespace: default
spec:
  url: oci://trial7h6srf.jfrog.io/headwind-helmoci
  interval: 5m
  type: oci
  secretRef:
    name: jfrog-oci-auth
---
# HelmRelease using busybox 1.0.0 - should discover 1.1.0
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: busybox-oci
  namespace: default
  annotations:
    headwind.sh/policy: "minor"
    headwind.sh/require-approval: "true"
spec:
  interval: 5m
  chart:
    spec:
      chart: busybox
      version: "1.0.0"
      sourceRef:
        kind: HelmRepository
        name: jfrog-oci
        namespace: default
  values:
    replicaCount: 1
